/**
 * Mock-Daten für Swipe Service
 * Analog zu auth.mocks.ts
 */

import { JobCard, BewerberCard } from './swipe.types';

/**
 * Mock Job Cards für Bewerber
 */
export const MOCK_JOB_CARDS: JobCard[] = [
  {
    id: 'job-1',
    companyName: 'TechStart GmbH',
    companyLogo: '🚀',
    jobTitle: 'Senior Frontend Developer',
    location: 'Berlin',
    salary: '60.000 - 80.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['React', 'TypeScript', 'React Native', 'Redux'],
    description: 'Wir suchen einen erfahrenen Frontend Developer für unser wachsendes Team. Du arbeitest an innovativen Mobile Apps und Web-Anwendungen.',
    benefits: ['Remote Work', 'Flexible Arbeitszeiten', 'Weiterbildungsbudget', 'Team Events'],
    createdAt: new Date('2024-11-01'),
  },
  {
    id: 'job-2',
    companyName: 'FinTech Solutions AG',
    companyLogo: '💰',
    jobTitle: 'Full Stack Developer',
    location: 'München',
    salary: '70.000 - 90.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['Node.js', 'React', 'PostgreSQL', 'Docker'],
    description: 'Entwickle mit uns die Zukunft des digitalen Bankings. Wir bieten ein modernes Tech-Stack und spannende Herausforderungen.',
    benefits: ['Company Bike', 'Betriebliche Altersvorsorge', 'Fitness-Studio', 'Sabbatical möglich'],
    createdAt: new Date('2024-11-02'),
  },
  {
    id: 'job-3',
    companyName: 'Creative Digital',
    companyLogo: '🎨',
    jobTitle: 'UI/UX Designer',
    location: 'Hamburg',
    salary: '50.000 - 65.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['Figma', 'Adobe XD', 'Prototyping', 'User Research'],
    description: 'Gestalte intuitive und ansprechende Benutzeroberflächen für unsere digitalen Produkte.',
    benefits: ['Kreatives Team', 'Moderne Tools', 'Flexible Zeiten'],
    createdAt: new Date('2024-11-03'),
  },
  {
    id: 'job-4',
    companyName: 'DataWorks AI',
    companyLogo: '🤖',
    jobTitle: 'Machine Learning Engineer',
    location: 'Frankfurt',
    salary: '75.000 - 95.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['Python', 'TensorFlow', 'PyTorch', 'AWS'],
    description: 'Entwickle KI-Lösungen für Enterprise-Kunden. Arbeite mit neuesten ML-Technologien.',
    benefits: ['Forschungsbudget', 'Konferenzbesuche', 'Stock Options', 'Remote möglich'],
    createdAt: new Date('2024-10-28'),
  },
  {
    id: 'job-5',
    companyName: 'GreenEnergy Tech',
    companyLogo: '🌱',
    jobTitle: 'Backend Developer',
    location: 'Stuttgart',
    salary: '55.000 - 70.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['Java', 'Spring Boot', 'Microservices', 'Kubernetes'],
    description: 'Hilf uns, nachhaltige Energielösungen digital zu machen. Impact mit Code!',
    benefits: ['Purpose-driven', 'E-Mobilität', 'Work-Life-Balance'],
    createdAt: new Date('2024-10-30'),
  },
  {
    id: 'job-6',
    companyName: 'Gaming Studios',
    companyLogo: '🎮',
    jobTitle: 'Game Developer',
    location: 'Köln',
    salary: '50.000 - 70.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['Unity', 'C#', '3D Graphics', 'Game Design'],
    description: 'Entwickle mit uns die nächste Generation von Mobile Games. Kreativität trifft Technik.',
    benefits: ['Creative Freedom', 'Game Room', 'Team Lunch', 'Flexible Hours'],
    createdAt: new Date('2024-10-25'),
  },
  {
    id: 'job-7',
    companyName: 'HealthTech Innovations',
    companyLogo: '🏥',
    jobTitle: 'Mobile Developer',
    location: 'Düsseldorf',
    salary: '60.000 - 75.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['React Native', 'Swift', 'Kotlin', 'Healthcare APIs'],
    description: 'Entwickle Apps, die das Gesundheitswesen revolutionieren. Sinnvolle Arbeit mit Impact.',
    benefits: ['Health Insurance Premium', 'Sportangebote', '30 Tage Urlaub'],
    createdAt: new Date('2024-10-29'),
  },
  {
    id: 'job-8',
    companyName: 'E-Commerce Plus',
    companyLogo: '🛒',
    jobTitle: 'DevOps Engineer',
    location: 'Leipzig',
    salary: '65.000 - 85.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['AWS', 'Terraform', 'CI/CD', 'Monitoring'],
    description: 'Baue und optimiere unsere Cloud-Infrastruktur für Millionen von Nutzern.',
    benefits: ['Cloud-Zertifizierungen', 'Bonus System', 'Remote First'],
    createdAt: new Date('2024-11-04'),
  },
  {
    id: 'job-9',
    companyName: 'Startup Ventures',
    companyLogo: '💡',
    jobTitle: 'Product Manager',
    location: 'Berlin',
    salary: '65.000 - 80.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['Product Strategy', 'Agile', 'User Stories', 'Analytics'],
    description: 'Leite die Produktentwicklung von 0 auf 1. Gestalte die Vision und Roadmap.',
    benefits: ['Equity', 'Gestaltungsfreiraum', 'Startup Spirit'],
    createdAt: new Date('2024-11-01'),
  },
  {
    id: 'job-10',
    companyName: 'Consulting Pro',
    companyLogo: '📊',
    jobTitle: 'IT Consultant',
    location: 'Frankfurt',
    salary: '70.000 - 90.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['Projektmanagement', 'Enterprise Architecture', 'SAP', 'Beratung'],
    description: 'Berate Konzerne bei ihrer digitalen Transformation. Vielfältige Projekte.',
    benefits: ['Firmenwagen', 'Reisebudget', 'Karriereentwicklung'],
    createdAt: new Date('2024-10-27'),
  },
  {
    id: 'job-11',
    companyName: 'MediaTech',
    companyLogo: '📱',
    jobTitle: 'iOS Developer',
    location: 'Hamburg',
    salary: '60.000 - 75.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['Swift', 'SwiftUI', 'Combine', 'App Store'],
    description: 'Entwickle Premium iOS Apps für Millionen von Nutzern weltweit.',
    benefits: ['MacBook Pro', 'iPhone', 'Weiterbildung', 'Remote möglich'],
    createdAt: new Date('2024-10-26'),
  },
  {
    id: 'job-12',
    companyName: 'CloudSystems',
    companyLogo: '☁️',
    jobTitle: 'Cloud Architect',
    location: 'München',
    salary: '80.000 - 100.000 €',
    employmentType: 'Vollzeit',
    requiredSkills: ['AWS', 'Azure', 'Architecture', 'Security'],
    description: 'Entwerfe skalierbare Cloud-Architekturen für Enterprise-Kunden.',
    benefits: ['Senior Position', 'Bonus', 'Company Car', 'Conferences'],
    createdAt: new Date('2024-10-24'),
  },
];

/**
 * Mock Bewerber Cards für Firmen
 */
export const MOCK_BEWERBER_CARDS: BewerberCard[] = [
  {
    id: 'bewerber-1',
    name: 'Max Mustermann',
    profileImage: '👨‍💻',
    title: 'Senior React Developer',
    location: 'Berlin',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL', 'AWS'],
    experience: '5 Jahre Erfahrung',
    availability: 'Sofort',
    bio: 'Passionierter Frontend Developer mit Fokus auf React und TypeScript. Liebe es, intuitive UIs zu bauen.',
    desiredSalary: '70.000 - 85.000 €',
    createdAt: new Date('2024-11-01'),
  },
  {
    id: 'bewerber-2',
    name: 'Anna Schmidt',
    profileImage: '👩‍💼',
    title: 'Product Designer',
    location: 'München',
    skills: ['Figma', 'UI/UX', 'Prototyping', 'User Research', 'Design Systems'],
    experience: '4 Jahre Erfahrung',
    availability: '1 Monat',
    bio: 'UX-Designerin mit Leidenschaft für nutzerorientiertes Design. Von Idee bis Launch.',
    desiredSalary: '60.000 - 75.000 €',
    createdAt: new Date('2024-11-02'),
  },
  {
    id: 'bewerber-3',
    name: 'Tom Weber',
    profileImage: '👨‍🔧',
    title: 'DevOps Engineer',
    location: 'Hamburg',
    skills: ['Docker', 'Kubernetes', 'CI/CD', 'AWS', 'Terraform'],
    experience: '6 Jahre Erfahrung',
    availability: 'Sofort',
    bio: 'Infrastructure as Code Enthusiast. Automatisiere alles was automatisierbar ist.',
    desiredSalary: '75.000 - 90.000 €',
    createdAt: new Date('2024-10-30'),
  },
  {
    id: 'bewerber-4',
    name: 'Lisa Müller',
    profileImage: '👩‍🎨',
    title: 'Full Stack Developer',
    location: 'Frankfurt',
    skills: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'REST APIs'],
    experience: '3 Jahre Erfahrung',
    availability: '1 Monat',
    bio: 'Vielseitige Entwicklerin mit Erfahrung in Frontend und Backend. Schnelle Auffassungsgabe.',
    desiredSalary: '55.000 - 70.000 €',
    createdAt: new Date('2024-11-03'),
  },
  {
    id: 'bewerber-5',
    name: 'David Klein',
    profileImage: '👨‍🚀',
    title: 'Mobile Developer',
    location: 'Stuttgart',
    skills: ['React Native', 'Swift', 'Kotlin', 'Firebase', 'App Store'],
    experience: '4 Jahre Erfahrung',
    availability: 'Sofort',
    bio: 'Native und Cross-Platform Mobile Apps sind meine Leidenschaft. Performance first!',
    desiredSalary: '60.000 - 75.000 €',
    createdAt: new Date('2024-10-28'),
  },
  {
    id: 'bewerber-6',
    name: 'Sarah Wagner',
    profileImage: '👩‍💻',
    title: 'Backend Engineer',
    location: 'Köln',
    skills: ['Python', 'Django', 'PostgreSQL', 'Redis', 'Microservices'],
    experience: '5 Jahre Erfahrung',
    availability: '3 Monate',
    bio: 'Skalierbare Backend-Systeme sind mein Ding. Clean Code Advocate.',
    desiredSalary: '65.000 - 80.000 €',
    createdAt: new Date('2024-10-29'),
  },
  {
    id: 'bewerber-7',
    name: 'Michael Bauer',
    profileImage: '👨‍🏫',
    title: 'Data Scientist',
    location: 'Düsseldorf',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'SQL', 'Data Viz'],
    experience: '3 Jahre Erfahrung',
    availability: 'Verhandelbar',
    bio: 'Verwandle Daten in wertvolle Insights. ML-Modelle von Konzept bis Production.',
    desiredSalary: '60.000 - 75.000 €',
    createdAt: new Date('2024-11-01'),
  },
  {
    id: 'bewerber-8',
    name: 'Julia Hoffmann',
    profileImage: '👩‍🔬',
    title: 'QA Engineer',
    location: 'Leipzig',
    skills: ['Test Automation', 'Selenium', 'Jest', 'CI/CD', 'Bug Tracking'],
    experience: '4 Jahre Erfahrung',
    availability: '1 Monat',
    bio: 'Qualität ist kein Zufall. Automatisierte Tests für robuste Software.',
    desiredSalary: '50.000 - 65.000 €',
    createdAt: new Date('2024-10-27'),
  },
  {
    id: 'bewerber-9',
    name: 'Chris Fischer',
    profileImage: '👨‍💼',
    title: 'Product Manager',
    location: 'Berlin',
    skills: ['Product Strategy', 'Agile', 'Roadmapping', 'Analytics', 'Stakeholder Mgmt'],
    experience: '6 Jahre Erfahrung',
    availability: 'Sofort',
    bio: 'Von der Vision zur erfolgreichen Produkteinführung. Nutzerorientiert und datengetrieben.',
    desiredSalary: '70.000 - 85.000 €',
    createdAt: new Date('2024-10-26'),
  },
  {
    id: 'bewerber-10',
    name: 'Nina Schneider',
    profileImage: '👩‍🚀',
    title: 'Security Engineer',
    location: 'München',
    skills: ['Security', 'Penetration Testing', 'OWASP', 'Encryption', 'Compliance'],
    experience: '5 Jahre Erfahrung',
    availability: '1 Monat',
    bio: 'Sichere Systeme sind meine Mission. Von Audit bis Incident Response.',
    desiredSalary: '70.000 - 85.000 €',
    createdAt: new Date('2024-10-25'),
  },
  {
    id: 'bewerber-11',
    name: 'Felix Richter',
    profileImage: '👨‍🎓',
    title: 'Junior Frontend Developer',
    location: 'Hamburg',
    skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'],
    experience: '1 Jahr Erfahrung',
    availability: 'Sofort',
    bio: 'Frischer Absolvent mit viel Motivation. Schnell lernend und teamorientiert.',
    desiredSalary: '40.000 - 50.000 €',
    createdAt: new Date('2024-11-04'),
  },
  {
    id: 'bewerber-12',
    name: 'Laura Meyer',
    profileImage: '👩‍⚕️',
    title: 'Technical Writer',
    location: 'Frankfurt',
    skills: ['Documentation', 'Technical Writing', 'API Docs', 'Markdown', 'Git'],
    experience: '3 Jahre Erfahrung',
    availability: 'Verhandelbar',
    bio: 'Mache komplexe Technik verständlich. Von Developer Docs bis User Guides.',
    desiredSalary: '45.000 - 60.000 €',
    createdAt: new Date('2024-10-24'),
  },
];
